"""Add FK constraints to material_issue_items for batch_id and bin_id

Revision ID: 2171986a9c1a
Revises: q17a8e15ff6
Create Date: 2026-05-09 12:26:26.857373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2171986a9c1a'
down_revision: Union[str, Sequence[str], None] = 'q17a8e15ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add ForeignKey constraints to material_issue_items for batch_id and bin_id."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_issue_items', schema=None) as batch_op:
        # Add FK constraint for batch_id -> batches.id
        batch_op.create_foreign_key(
            'fk_material_issue_items_batch_id',
            'batches',
            ['batch_id'],
            ['id'],
            ondelete='SET NULL'
        )
        # Add FK constraint for bin_id -> warehouse_bins.id
        batch_op.create_foreign_key(
            'fk_material_issue_items_bin_id',
            'warehouse_bins',
            ['bin_id'],
            ['id'],
            ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove ForeignKey constraints from material_issue_items."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_issue_items', schema=None) as batch_op:
        # Drop FK constraints
        batch_op.drop_constraint('fk_material_issue_items_bin_id', type_='foreignkey')
        batch_op.drop_constraint('fk_material_issue_items_batch_id', type_='foreignkey')

    # ### end Alembic commands ###
