"""add_item_sub_classes

Revision ID: 4274b7f69a1b
Revises: 2026_07_03_mi_item_trace_fields
Create Date: 2026-07-04 12:46:14.640632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4274b7f69a1b'
down_revision: Union[str, Sequence[str], None] = '2026_07_03_mi_item_trace_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # FIX: Drop child tables that reference trip_sheets BEFORE dropping trip_sheets
    # to avoid FK constraint violation (trip_sheet_packages_ibfk_1)
    op.drop_table('trip_sheet_package_items')
    with op.batch_alter_table('trip_sheet_packages', schema=None) as batch_op:
        batch_op.drop_index('ix_trip_sheet_packages_package_number')
    op.drop_table('trip_sheet_packages')

    # FIX: Use raw SQL with IF EXISTS for the index drop because some server
    # databases may not have this index (schema drift between environments)
    op.execute('DROP INDEX IF EXISTS ix_trip_sheets_trip_number ON trip_sheets')

    op.drop_table('trip_sheets')
    with op.batch_alter_table('employee_item_permissions', schema=None) as batch_op:
        batch_op.drop_index('uq_employee_item_permissions_scope')

    op.drop_table('employee_item_permissions')
    with op.batch_alter_table('item_boms', schema=None) as batch_op:
        batch_op.drop_index('bom_code')

    op.drop_table('item_boms')
    with op.batch_alter_table('approval_delegations', schema=None) as batch_op:
        batch_op.drop_index('ix_appdel_delegatee_active')
        batch_op.drop_index('ix_appdel_delegator_active')

    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_ar_status_requested')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('purchase_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('warranty_expiry',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('barcode_registry', schema=None) as batch_op:
        batch_op.alter_column('barcode_data',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='JSON data encoded in QR',
               existing_nullable=True)

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.alter_column('manufacturing_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('expiry_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('uq_item_batch')

    with op.batch_alter_table('boms', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'positions', ['position_id'], ['id'])

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_constraint('fk_brands_manufacturer', type_='foreignkey')

    with op.batch_alter_table('business_rule_executions', schema=None) as batch_op:
        batch_op.alter_column('fired_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('business_rules', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('chart_of_accounts', schema=None) as batch_op:
        batch_op.drop_index('idx_coa_org')

    with op.batch_alter_table('consumption_entries', schema=None) as batch_op:
        batch_op.alter_column('consumption_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index('idx_consumption_source_issue')
        batch_op.drop_column('source_issue_id')

    with op.batch_alter_table('consumption_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'uom', ['uom_id'], ['id'])

    with op.batch_alter_table('consumption_returns', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.alter_column('cn_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('delivery_orders', schema=None) as batch_op:
        batch_op.alter_column('delivery_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('dispatch_handovers', schema=None) as batch_op:
        batch_op.alter_column('otp_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'HANDED_OVER', 'REJECTED', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_server_default=sa.text("'PENDING'"))

    with op.batch_alter_table('dispatch_orders', schema=None) as batch_op:
        batch_op.alter_column('destination_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('WAREHOUSE', 'USER', 'BRANCH', 'DEALER', name='destination_type_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'USER'"))
        batch_op.alter_column('dispatch_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('THIRD_PARTY', 'COURIER', 'OWN_VEHICLE', 'IN_PERSON', name='dispatch_type_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'THIRD_PARTY'"))
        batch_op.alter_column('receiver_id_proof_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('AADHAR', 'PAN', 'DRIVING_LICENSE', 'EMPLOYEE_ID', 'NONE', name='id_proof_enum'),
               nullable=True,
               existing_server_default=sa.text("'NONE'"))
        batch_op.alter_column('goods_condition_on_delivery',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('GOOD', 'DAMAGED', 'PARTIAL', 'DISCREPANCY', name='goods_cond_enum'),
               nullable=True,
               existing_server_default=sa.text("'GOOD'"))
        batch_op.create_foreign_key(None, 'warehouses', ['destination_warehouse_id'], ['id'])
        batch_op.create_foreign_key(None, 'material_issues', ['material_issue_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['destination_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['delivery_acknowledged_by_id'], ['id'])
        batch_op.drop_column('lmdc_code')
        batch_op.drop_column('trip_sheet_id')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index('ft_emp_name_code', mysql_prefix='FULLTEXT')
        batch_op.drop_index('idx_employees_email')
        batch_op.drop_index('idx_employees_name')
        batch_op.drop_index('idx_employees_phone')
        batch_op.drop_index('idx_employees_status')

    with op.batch_alter_table('fiscal_years', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index('uq_fy_org_label')

    with op.batch_alter_table('gate_passes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'approved', 'gate_in', 'gate_out', 'completed', 'cancelled'),
               nullable=True,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('goods_receipt_notes', schema=None) as batch_op:
        batch_op.alter_column('grn_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('supplier_invoice_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('grn_items', schema=None) as batch_op:
        batch_op.alter_column('manufacturing_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('expiry_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('idx_grn_items_item_id')

    with op.batch_alter_table('indent_acknowledgements', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'warehouses', ['warehouse_id'], ['id'])

    with op.batch_alter_table('indent_items', schema=None) as batch_op:
        batch_op.drop_index('idx_fulfillment_status')
        batch_op.drop_index('idx_reserved_at')

    with op.batch_alter_table('indents', schema=None) as batch_op:
        batch_op.alter_column('indent_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('required_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('idx_indents_source_bom')
        batch_op.drop_index('ix_indents_raised_by_created')

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'uom', ['uom_id'], ['id'])

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('issue_returns', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('item_attribute_values', schema=None) as batch_op:
        batch_op.drop_index('ix_item_attribute_values_uom_category_id')
        batch_op.drop_index('uq_iav_item_attr')
        batch_op.create_foreign_key(None, 'uom_categories', ['uom_category_id'], ['id'])

    with op.batch_alter_table('item_attributes', schema=None) as batch_op:
        batch_op.drop_index('ix_item_attributes_uom_category_id')
        batch_op.drop_index('uq_attr_category_code')
        batch_op.create_foreign_key(None, 'uom_categories', ['uom_category_id'], ['id'])

    with op.batch_alter_table('item_categories', schema=None) as batch_op:
        batch_op.drop_index('idx_itemcat_prefix')

    with op.batch_alter_table('item_features', schema=None) as batch_op:
        batch_op.drop_index('ux_item_features_item_feature')

    with op.batch_alter_table('item_master_kit_components', schema=None) as batch_op:
        batch_op.drop_index('ix_item_master_kit_components_item_id')
        batch_op.drop_constraint('fk_item_master_kit_components_uom_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'uom', ['uom_id'], ['id'])

    with op.batch_alter_table('item_packaging', schema=None) as batch_op:
        batch_op.drop_index('idx_item_packaging_tree')
        batch_op.drop_constraint('fk_item_packing_weight_uom_id', type_='foreignkey')
        batch_op.drop_constraint('fk_item_packing_parent_packaging_id', type_='foreignkey')
        batch_op.drop_constraint('fk_item_packing_dimension_uom_id', type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('parent_packaging_id')
        batch_op.drop_column('quantity_in_parent')
        batch_op.drop_column('is_active')
        batch_op.drop_column('weight_uom_id')
        batch_op.drop_column('gross_weight')
        batch_op.drop_column('tare_weight')
        batch_op.drop_column('length')
        batch_op.drop_column('barcode_gtin')
        batch_op.drop_column('dimension_uom_id')
        batch_op.drop_column('width')
        batch_op.drop_column('barcode_sscc')
        batch_op.drop_column('height')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('special_storage_condition',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('storage_breakable',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('special_transport_condition',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('transport_breakable',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index('idx_item_form_code')
        batch_op.drop_index('idx_items_feature_id')
        batch_op.drop_index('ix_items_uom_category_id')
        batch_op.drop_index('uq_items_name_active_ci')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_constraint('fk_items_item_sub_class_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'features', ['feature_id'], ['id'])
        batch_op.create_foreign_key(None, 'brands', ['brand'], ['code'])
        batch_op.create_foreign_key(None, 'uom_categories', ['uom_category_id'], ['id'])
        batch_op.create_foreign_key(None, 'item_sub_classes', ['item_sub_class_id'], ['id'])
        batch_op.drop_column('unit_weight_kg')
        batch_op.drop_column('volume')
        batch_op.drop_column('unit_volume_cm3')
        batch_op.drop_column('width_cm')
        batch_op.drop_column('weight')
        batch_op.drop_column('average_daily_consumption')
        batch_op.drop_column('reorder_alert_enabled')
        batch_op.drop_column('generic_name')
        batch_op.drop_column('height_cm')
        batch_op.drop_column('weight_uom')
        batch_op.drop_column('length_cm')
        batch_op.drop_column('volume_uom')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.alter_column('entry_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index('idx_je_org')
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('landed_costs', schema=None) as batch_op:
        batch_op.drop_column('tax_treatment')

    with op.batch_alter_table('logistics_main_dispatch_orders', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['destination_user_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('lmdc_code')
        batch_op.drop_column('trip_sheet_id')

    with op.batch_alter_table('logistics_sub_dispatch_orders', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'positions', ['custodian_position_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['handed_over_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['received_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('material_issue_items', schema=None) as batch_op:
        batch_op.alter_column('batch_number_text',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='Free-text source batch reference for non-central WH (no FK, no ledger validation)',
               existing_nullable=True)
        batch_op.alter_column('bin_code_text',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='Free-text source bin/location reference for non-central WH',
               existing_nullable=True)
        batch_op.drop_constraint('fk_material_issue_items_batch_id', type_='foreignkey')
        batch_op.drop_constraint('fk_material_issue_items_bin_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'warehouse_bins', ['bin_id'], ['id'])
        batch_op.create_foreign_key(None, 'uom', ['uom_id'], ['id'])
        batch_op.create_foreign_key(None, 'batches', ['batch_id'], ['id'])

    with op.batch_alter_table('material_issues', schema=None) as batch_op:
        batch_op.alter_column('issue_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_constraint('fk_material_issues_destination_warehouse', type_='foreignkey')
        batch_op.create_foreign_key(None, 'warehouses', ['destination_warehouse_id'], ['id'])
        batch_op.drop_column('issued_to_employee_code')
        batch_op.drop_column('cost_center')
        batch_op.drop_column('trip_sheet_id')

    with op.batch_alter_table('material_request_items', schema=None) as batch_op:
        batch_op.drop_index('idx_material_request_items_item_id')

    with op.batch_alter_table('material_requests', schema=None) as batch_op:
        batch_op.alter_column('request_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('required_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('idx_mr_indent')

    with op.batch_alter_table('mr_indent_links', schema=None) as batch_op:
        batch_op.drop_index('ix_mril_indent')
        batch_op.drop_index('ix_mril_mr')
        batch_op.drop_index('uq_mril_mr_indent_item')

    with op.batch_alter_table('number_series', schema=None) as batch_op:
        batch_op.drop_index('idx_numseries_fy')
        batch_op.drop_index('ix_ns_module_doc_fy')
        batch_op.drop_index('uq_ns')
        batch_op.create_index('uq_ns_module_doc_fy', ['module', 'document_type', 'fiscal_year'], unique=True)
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('offices', schema=None) as batch_op:
        batch_op.drop_index('ft_office_name', mysql_prefix='FULLTEXT')
        batch_op.drop_index('idx_offices_cluster')
        batch_op.drop_index('idx_offices_district')
        batch_op.drop_index('idx_offices_state')

    with op.batch_alter_table('packing_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'uom', ['uom_id'], ['id'])

    with op.batch_alter_table('packing_orders', schema=None) as batch_op:
        batch_op.drop_index('idx_packing_orders_mi')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index('uq_perm')

    with op.batch_alter_table('picking_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'uom', ['uom_id'], ['id'])

    with op.batch_alter_table('picking_orders', schema=None) as batch_op:
        batch_op.drop_index('idx_picking_orders_mi')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index('ft_pos_name_code', mysql_prefix='FULLTEXT')
        batch_op.drop_index('idx_positions_department')
        batch_op.drop_index('idx_positions_name')
        batch_op.drop_index('idx_positions_office_id')
        batch_op.drop_index('idx_positions_project_id')
        batch_op.drop_index('idx_positions_role_name')
        batch_op.drop_index('idx_positions_status')

    with op.batch_alter_table('price_list_items', schema=None) as batch_op:
        batch_op.alter_column('valid_from',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('valid_to',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('idx_price_list_items_item_id')

    with op.batch_alter_table('price_lists', schema=None) as batch_op:
        batch_op.alter_column('valid_from',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('valid_to',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('idx_projects_name')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('po_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('expected_delivery_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('draft', 'pending_approval', 'approved', 'accepted', 'rejected', 'partially_received', 'received', 'closed', 'cancelled'),
               nullable=True,
               existing_server_default=sa.text("'draft'"))
        batch_op.alter_column('supplier_acknowledgement',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('purchase_return_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'uom', ['uom_id'], ['id'])

    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.alter_column('return_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('putaway_items', schema=None) as batch_op:
        batch_op.alter_column('batch_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
        batch_op.drop_constraint('fk_putaway_items_batch_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'uom', ['uom_id'], ['id'])
        batch_op.create_foreign_key(None, 'grn_items', ['grn_item_id'], ['id'])
        batch_op.create_foreign_key(None, 'batches', ['batch_id'], ['id'])

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('quotation_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('valid_until',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('subtotal',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('vehicle_cost',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('with_vehicle',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index('idx_quotations_rfq_number')
        batch_op.create_index(batch_op.f('ix_quotations_rfq_number'), ['rfq_number'], unique=False)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index('uq_role_perm')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('idx_roles_name')
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('delivery_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('serial_numbers', schema=None) as batch_op:
        batch_op.drop_index('uq_item_serial')

    with op.batch_alter_table('stock_audit_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'uom', ['uom_id'], ['id'])

    with op.batch_alter_table('stock_audits', schema=None) as batch_op:
        batch_op.alter_column('audit_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('stock_balance', schema=None) as batch_op:
        batch_op.drop_index('uq_stock_bal')
        batch_op.create_index('idx_sb_composite', ['item_id', 'warehouse_id', 'bin_id', 'batch_id'], unique=False)
        batch_op.create_unique_constraint('uq_stock_balance_key', ['item_id', 'warehouse_id', 'bin_id', 'batch_id'])
        batch_op.create_foreign_key(None, 'warehouse_bins', ['bin_id'], ['id'])
        batch_op.create_foreign_key(None, 'batches', ['batch_id'], ['id'])

    with op.batch_alter_table('stock_ledger', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=mysql.ENUM('grn', 'putaway', 'pick', 'pack', 'dispatch', 'transfer_in', 'transfer_out', 'adjustment', 'consumption', 'return', 'opening', 'material_issue', 'stock_entry'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('posting_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index('idx_stock_ledger_item_wh_date')

    with op.batch_alter_table('stock_transfer_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'uom', ['uom_id'], ['id'])

    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.alter_column('transfer_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('expected_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('uom', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('abbreviation',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_index('ix_uom_category_id')
        batch_op.create_foreign_key(None, 'uom_categories', ['category_id'], ['id'])

    with op.batch_alter_table('uom_categories', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'uom', ['base_uom_id'], ['id'])

    with op.batch_alter_table('uom_conversions', schema=None) as batch_op:
        batch_op.alter_column('conversion_factor',
               existing_type=mysql.DECIMAL(precision=15, scale=6),
               type_=sa.Numeric(precision=24, scale=12),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'uom_categories', ['category_id'], ['id'])

    with op.batch_alter_table('user_group_members', schema=None) as batch_op:
        batch_op.drop_index('uq_ugm_group_user')

    with op.batch_alter_table('user_group_permissions', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               nullable=True,
               existing_server_default=sa.text("'view'"))
        batch_op.drop_index('ix_ugp_entity')
        batch_op.drop_index('uq_ugp_group_entity_action')

    with op.batch_alter_table('user_item_permissions', schema=None) as batch_op:
        batch_op.drop_index('uq_user_item_permissions_scope')

    with op.batch_alter_table('user_projects', schema=None) as batch_op:
        batch_op.drop_index('uq_user_project')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index('uq_user_role')

    with op.batch_alter_table('user_warehouses', schema=None) as batch_op:
        batch_op.drop_index('idx_user_id')
        batch_op.drop_index('uq_user_wh_role')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_organization_id')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('vehicle_code',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('vehicle_number',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('service_code')

    with op.batch_alter_table('vendor_contracts', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('vendor_items', schema=None) as batch_op:
        batch_op.drop_index('idx_vendor_items_item_id')

    with op.batch_alter_table('vendor_ratings', schema=None) as batch_op:
        batch_op.alter_column('period_from',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('period_to',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('onboarded_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('idx_vendor_license_expiry')
        batch_op.drop_index('ix_vendors_vendor_category_id')
        batch_op.drop_index('ix_vendors_vendor_type_id')
        batch_op.create_foreign_key(None, 'vendor_types', ['vendor_type_id'], ['id'])

    with op.batch_alter_table('warehouse_bins', schema=None) as batch_op:
        batch_op.drop_index('uq_wh_bin')

    with op.batch_alter_table('warehouse_lines', schema=None) as batch_op:
        batch_op.drop_index('uq_wh_line')

    with op.batch_alter_table('warehouse_locations', schema=None) as batch_op:
        batch_op.drop_index('uq_wh_loc')

    with op.batch_alter_table('warehouse_racks', schema=None) as batch_op:
        batch_op.drop_index('uq_wh_rack')

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index('idx_warehouses_office_id')

    with op.batch_alter_table('wave_plans', schema=None) as batch_op:
        batch_op.alter_column('wave_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wave_plans', schema=None) as batch_op:
        batch_op.alter_column('wave_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index('idx_warehouses_office_id', ['office_id'], unique=False)

    with op.batch_alter_table('warehouse_racks', schema=None) as batch_op:
        batch_op.create_index('uq_wh_rack', ['line_id', 'code'], unique=True)

    with op.batch_alter_table('warehouse_locations', schema=None) as batch_op:
        batch_op.create_index('uq_wh_loc', ['warehouse_id', 'code'], unique=True)

    with op.batch_alter_table('warehouse_lines', schema=None) as batch_op:
        batch_op.create_index('uq_wh_line', ['location_id', 'code'], unique=True)

    with op.batch_alter_table('warehouse_bins', schema=None) as batch_op:
        batch_op.create_index('uq_wh_bin', ['rack_id', 'code'], unique=True)

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_vendors_vendor_type_id', ['vendor_type_id'], unique=False)
        batch_op.create_index('ix_vendors_vendor_category_id', ['vendor_category_id'], unique=False)
        batch_op.create_index('idx_vendor_license_expiry', ['drug_license_expiry'], unique=False)
        batch_op.alter_column('onboarded_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('vendor_ratings', schema=None) as batch_op:
        batch_op.alter_column('period_to',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('period_from',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('vendor_items', schema=None) as batch_op:
        batch_op.create_index('idx_vendor_items_item_id', ['item_id'], unique=False)

    with op.batch_alter_table('vendor_contracts', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_code', mysql.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('vehicle_number',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('vehicle_code',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_organization_id', ['organization_id'], unique=False)

    with op.batch_alter_table('user_warehouses', schema=None) as batch_op:
        batch_op.create_index('uq_user_wh_role', ['user_id', 'warehouse_id', 'role_id'], unique=True)
        batch_op.create_index('idx_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index('uq_user_role', ['user_id', 'role_id'], unique=True)

    with op.batch_alter_table('user_projects', schema=None) as batch_op:
        batch_op.create_index('uq_user_project', ['user_id', 'project_id'], unique=True)

    with op.batch_alter_table('user_item_permissions', schema=None) as batch_op:
        batch_op.create_index('uq_user_item_permissions_scope', ['user_id', 'entity_type', 'entity_id', 'action'], unique=True)

    with op.batch_alter_table('user_group_permissions', schema=None) as batch_op:
        batch_op.create_index('uq_ugp_group_entity_action', ['group_id', 'entity_type', 'entity_id', 'action'], unique=True)
        batch_op.create_index('ix_ugp_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.alter_column('action',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               nullable=False,
               existing_server_default=sa.text("'view'"))

    with op.batch_alter_table('user_group_members', schema=None) as batch_op:
        batch_op.create_index('uq_ugm_group_user', ['group_id', 'user_id'], unique=True)

    with op.batch_alter_table('uom_conversions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('conversion_factor',
               existing_type=sa.Numeric(precision=24, scale=12),
               type_=mysql.DECIMAL(precision=15, scale=6),
               existing_nullable=False)

    with op.batch_alter_table('uom_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('uom', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_uom_category_id', ['category_id'], unique=False)
        batch_op.alter_column('abbreviation',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.alter_column('expected_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('transfer_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('stock_transfer_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('stock_ledger', schema=None) as batch_op:
        batch_op.create_index('idx_stock_ledger_item_wh_date', ['item_id', 'warehouse_id', 'posting_date'], unique=False)
        batch_op.alter_column('posting_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('transaction_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('grn', 'putaway', 'pick', 'pack', 'dispatch', 'transfer_in', 'transfer_out', 'adjustment', 'consumption', 'return', 'opening', 'material_issue', 'stock_entry'),
               existing_nullable=False)

    with op.batch_alter_table('stock_balance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_stock_balance_key', type_='unique')
        batch_op.drop_index('idx_sb_composite')
        batch_op.create_index('uq_stock_bal', ['item_id', 'warehouse_id', 'bin_id', 'batch_id'], unique=True)

    with op.batch_alter_table('stock_audits', schema=None) as batch_op:
        batch_op.alter_column('audit_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('stock_audit_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('serial_numbers', schema=None) as batch_op:
        batch_op.create_index('uq_item_serial', ['item_id', 'serial_number'], unique=True)

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.alter_column('delivery_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('order_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('idx_roles_name', ['name'], unique=False)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index('uq_role_perm', ['role_id', 'permission_id'], unique=True)

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotations_rfq_number'))
        batch_op.create_index('idx_quotations_rfq_number', ['rfq_number'], unique=False)
        batch_op.alter_column('with_vehicle',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('vehicle_cost',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('subtotal',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('valid_until',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('quotation_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('putaway_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_putaway_items_batch_id', 'batches', ['batch_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('batch_id',
               existing_type=mysql.BIGINT(),
               nullable=True)

    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.alter_column('return_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('purchase_return_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('supplier_acknowledgement',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('draft', 'pending_approval', 'approved', 'accepted', 'rejected', 'partially_received', 'received', 'closed', 'cancelled'),
               nullable=False,
               existing_server_default=sa.text("'draft'"))
        batch_op.alter_column('expected_delivery_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('po_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('idx_projects_name', ['name'], unique=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('price_lists', schema=None) as batch_op:
        batch_op.alter_column('valid_to',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('valid_from',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('price_list_items', schema=None) as batch_op:
        batch_op.create_index('idx_price_list_items_item_id', ['item_id'], unique=False)
        batch_op.alter_column('valid_to',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('valid_from',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index('idx_positions_status', ['status'], unique=False)
        batch_op.create_index('idx_positions_role_name', ['role_name'], unique=False)
        batch_op.create_index('idx_positions_project_id', ['project_id'], unique=False)
        batch_op.create_index('idx_positions_office_id', ['office_id'], unique=False)
        batch_op.create_index('idx_positions_name', ['name'], unique=False)
        batch_op.create_index('idx_positions_department', ['department'], unique=False)
        batch_op.create_index('ft_pos_name_code', ['name', 'code', 'role_name', 'department'], unique=False, mysql_prefix='FULLTEXT')

    with op.batch_alter_table('picking_orders', schema=None) as batch_op:
        batch_op.create_index('idx_picking_orders_mi', ['material_issue_id'], unique=False)

    with op.batch_alter_table('picking_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index('uq_perm', ['module', 'action', 'resource'], unique=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('packing_orders', schema=None) as batch_op:
        batch_op.create_index('idx_packing_orders_mi', ['material_issue_id'], unique=False)

    with op.batch_alter_table('packing_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('offices', schema=None) as batch_op:
        batch_op.create_index('idx_offices_state', ['state'], unique=False)
        batch_op.create_index('idx_offices_district', ['district'], unique=False)
        batch_op.create_index('idx_offices_cluster', ['cluster'], unique=False)
        batch_op.create_index('ft_office_name', ['name', 'state', 'district', 'cluster'], unique=False, mysql_prefix='FULLTEXT')

    with op.batch_alter_table('number_series', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('uq_ns_module_doc_fy')
        batch_op.create_index('uq_ns', ['prefix', 'module', 'fiscal_year'], unique=True)
        batch_op.create_index('ix_ns_module_doc_fy', ['module', 'document_type', 'fiscal_year'], unique=False)
        batch_op.create_index('idx_numseries_fy', ['module', 'document_type', 'fiscal_year'], unique=False)

    with op.batch_alter_table('mr_indent_links', schema=None) as batch_op:
        batch_op.create_index('uq_mril_mr_indent_item', ['mr_id', 'indent_item_id'], unique=True)
        batch_op.create_index('ix_mril_mr', ['mr_id'], unique=False)
        batch_op.create_index('ix_mril_indent', ['indent_id'], unique=False)

    with op.batch_alter_table('material_requests', schema=None) as batch_op:
        batch_op.create_index('idx_mr_indent', ['indent_id'], unique=False)
        batch_op.alter_column('required_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('request_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('material_request_items', schema=None) as batch_op:
        batch_op.create_index('idx_material_request_items_item_id', ['item_id'], unique=False)

    with op.batch_alter_table('material_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_sheet_id', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cost_center', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('issued_to_employee_code', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_material_issues_destination_warehouse', 'warehouses', ['destination_warehouse_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('issue_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('material_issue_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_material_issue_items_bin_id', 'warehouse_bins', ['bin_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_material_issue_items_batch_id', 'batches', ['batch_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('bin_code_text',
               existing_type=mysql.VARCHAR(length=100),
               comment='Free-text source bin/location reference for non-central WH',
               existing_nullable=True)
        batch_op.alter_column('batch_number_text',
               existing_type=mysql.VARCHAR(length=100),
               comment='Free-text source batch reference for non-central WH (no FK, no ledger validation)',
               existing_nullable=True)

    with op.batch_alter_table('logistics_sub_dispatch_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('logistics_main_dispatch_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_sheet_id', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lmdc_code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('landed_costs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_treatment', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=40), nullable=True))

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('idx_je_org', ['organization_id'], unique=False)
        batch_op.alter_column('entry_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume_uom', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('length_cm', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('weight_uom', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('height_cm', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('generic_name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('reorder_alert_enabled', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('average_daily_consumption', mysql.DECIMAL(precision=15, scale=3), nullable=True))
        batch_op.add_column(sa.Column('weight', mysql.DECIMAL(precision=10, scale=3), nullable=True))
        batch_op.add_column(sa.Column('width_cm', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('unit_volume_cm3', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('volume', mysql.DECIMAL(precision=10, scale=3), nullable=True))
        batch_op.add_column(sa.Column('unit_weight_kg', mysql.DECIMAL(precision=10, scale=3), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_items_item_sub_class_id', 'item_sub_classes', ['item_sub_class_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('uq_items_name_active_ci', [], unique=True)
        batch_op.create_index('ix_items_uom_category_id', ['uom_category_id'], unique=False)
        batch_op.create_index('idx_items_feature_id', ['feature_id'], unique=False)
        batch_op.create_index('idx_item_form_code', ['dosage_form_code'], unique=False)
        batch_op.alter_column('transport_breakable',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('special_transport_condition',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('storage_breakable',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('special_storage_condition',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('item_packaging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', mysql.DECIMAL(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('barcode_sscc', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.add_column(sa.Column('width', mysql.DECIMAL(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('dimension_uom_id', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('barcode_gtin', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.add_column(sa.Column('length', mysql.DECIMAL(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('tare_weight', mysql.DECIMAL(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('gross_weight', mysql.DECIMAL(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('weight_uom_id', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('quantity_in_parent', mysql.DECIMAL(precision=15, scale=4), nullable=True))
        batch_op.add_column(sa.Column('parent_packaging_id', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
        batch_op.create_foreign_key('fk_item_packing_dimension_uom_id', 'uom', ['dimension_uom_id'], ['id'])
        batch_op.create_foreign_key('fk_item_packing_parent_packaging_id', 'item_packaging', ['parent_packaging_id'], ['id'])
        batch_op.create_foreign_key('fk_item_packing_weight_uom_id', 'uom', ['weight_uom_id'], ['id'])
        batch_op.create_index('idx_item_packaging_tree', ['item_id', 'parent_packaging_id'], unique=False)

    with op.batch_alter_table('item_master_kit_components', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_item_master_kit_components_uom_id', 'uom', ['uom_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('ix_item_master_kit_components_item_id', ['item_id'], unique=False)

    with op.batch_alter_table('item_features', schema=None) as batch_op:
        batch_op.create_index('ux_item_features_item_feature', ['item_id', 'feature_id'], unique=True)

    with op.batch_alter_table('item_categories', schema=None) as batch_op:
        batch_op.create_index('idx_itemcat_prefix', ['code_prefix'], unique=False)

    with op.batch_alter_table('item_attributes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('uq_attr_category_code', ['category_id', 'code'], unique=True)
        batch_op.create_index('ix_item_attributes_uom_category_id', ['uom_category_id'], unique=False)

    with op.batch_alter_table('item_attribute_values', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('uq_iav_item_attr', ['item_id', 'attribute_id'], unique=True)
        batch_op.create_index('ix_item_attribute_values_uom_category_id', ['uom_category_id'], unique=False)

    with op.batch_alter_table('issue_returns', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('invoice_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('indents', schema=None) as batch_op:
        batch_op.create_index('ix_indents_raised_by_created', ['raised_by', 'created_at'], unique=False)
        batch_op.create_index('idx_indents_source_bom', ['source_bom_id'], unique=False)
        batch_op.alter_column('required_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('indent_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('indent_items', schema=None) as batch_op:
        batch_op.create_index('idx_reserved_at', ['reserved_at'], unique=False)
        batch_op.create_index('idx_fulfillment_status', ['fulfillment_status'], unique=False)

    with op.batch_alter_table('indent_acknowledgements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('grn_items', schema=None) as batch_op:
        batch_op.create_index('idx_grn_items_item_id', ['item_id'], unique=False)
        batch_op.alter_column('expiry_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('manufacturing_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('goods_receipt_notes', schema=None) as batch_op:
        batch_op.alter_column('supplier_invoice_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('grn_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('gate_passes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'approved', 'gate_in', 'gate_out', 'completed', 'cancelled'),
               nullable=False,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('fiscal_years', schema=None) as batch_op:
        batch_op.create_index('uq_fy_org_label', ['organization_id', 'year_label'], unique=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index('idx_employees_status', ['status'], unique=False)
        batch_op.create_index('idx_employees_phone', ['phone'], unique=False)
        batch_op.create_index('idx_employees_name', ['name'], unique=False)
        batch_op.create_index('idx_employees_email', ['email'], unique=False)
        batch_op.create_index('ft_emp_name_code', ['name', 'employee_code'], unique=False, mysql_prefix='FULLTEXT')

    with op.batch_alter_table('dispatch_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_sheet_id', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lmdc_code', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('goods_condition_on_delivery',
               existing_type=sa.Enum('GOOD', 'DAMAGED', 'PARTIAL', 'DISCREPANCY', name='goods_cond_enum'),
               type_=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'GOOD'"))
        batch_op.alter_column('receiver_id_proof_type',
               existing_type=sa.Enum('AADHAR', 'PAN', 'DRIVING_LICENSE', 'EMPLOYEE_ID', 'NONE', name='id_proof_enum'),
               type_=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'NONE'"))
        batch_op.alter_column('dispatch_type',
               existing_type=sa.Enum('THIRD_PARTY', 'COURIER', 'OWN_VEHICLE', 'IN_PERSON', name='dispatch_type_enum'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'THIRD_PARTY'"))
        batch_op.alter_column('destination_type',
               existing_type=sa.Enum('WAREHOUSE', 'USER', 'BRANCH', 'DEALER', name='destination_type_enum'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'USER'"))

    with op.batch_alter_table('dispatch_handovers', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'HANDED_OVER', 'REJECTED', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'"))
        batch_op.alter_column('otp_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('delivery_orders', schema=None) as batch_op:
        batch_op.alter_column('delivery_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.alter_column('cn_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('consumption_returns', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('consumption_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('consumption_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_issue_id', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_index('idx_consumption_source_issue', ['source_issue_id'], unique=False)
        batch_op.alter_column('consumption_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('chart_of_accounts', schema=None) as batch_op:
        batch_op.create_index('idx_coa_org', ['organization_id'], unique=False)

    with op.batch_alter_table('business_rules', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('business_rule_executions', schema=None) as batch_op:
        batch_op.alter_column('fired_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_brands_manufacturer', 'vendors', ['manufacturer_id'], ['id'])

    with op.batch_alter_table('boms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index('uq_item_batch', ['item_id', 'batch_number'], unique=True)
        batch_op.alter_column('expiry_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('manufacturing_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('barcode_registry', schema=None) as batch_op:
        batch_op.alter_column('barcode_data',
               existing_type=mysql.TEXT(),
               comment='JSON data encoded in QR',
               existing_nullable=True)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('warranty_expiry',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('purchase_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index('ix_ar_status_requested', ['status', 'requested_at'], unique=False)

    with op.batch_alter_table('approval_delegations', schema=None) as batch_op:
        batch_op.create_index('ix_appdel_delegator_active', ['delegator_id', 'is_active'], unique=False)
        batch_op.create_index('ix_appdel_delegatee_active', ['delegatee_id', 'is_active'], unique=False)

    op.create_table('trip_sheet_package_items',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('package_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('material_issue_item_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('qty', mysql.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['material_issue_item_id'], ['material_issue_items.id'], name='trip_sheet_package_items_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['trip_sheet_packages.id'], name='trip_sheet_package_items_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('trip_sheet_packages',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('trip_sheet_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('material_issue_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('mdo_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('package_number', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('package_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('lmdc_code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('gross_weight', mysql.DECIMAL(precision=15, scale=3), nullable=True),
    sa.Column('net_weight', mysql.DECIMAL(precision=15, scale=3), nullable=True),
    sa.Column('dimensions', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('remarks', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.ForeignKeyConstraint(['material_issue_id'], ['material_issues.id'], name='trip_sheet_packages_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mdo_id'], ['logistics_main_dispatch_orders.id'], name='trip_sheet_packages_ibfk_3', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_sheet_id'], ['trip_sheets.id'], name='trip_sheet_packages_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('trip_sheet_packages', schema=None) as batch_op:
        batch_op.create_index('ix_trip_sheet_packages_package_number', ['package_number'], unique=True)

    op.create_table('item_boms',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('bom_code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('project_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('document_types', mysql.JSON(), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_by', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='item_boms_ibfk_1'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='item_boms_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('item_boms', schema=None) as batch_op:
        batch_op.create_index('bom_code', ['bom_code'], unique=True)

    op.create_table('employee_item_permissions',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('employee_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('entity_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('entity_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('action', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='employee_item_permissions_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('employee_item_permissions', schema=None) as batch_op:
        batch_op.create_index('uq_employee_item_permissions_scope', ['employee_id', 'entity_type', 'entity_id', 'action'], unique=True)

    op.create_table('trip_sheets',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('trip_number', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('warehouse_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('transporter_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('vehicle_no', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('driver_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=150), nullable=True),
    sa.Column('driver_phone', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('status', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('remarks', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_by', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='trip_sheets_ibfk_3'),
    sa.ForeignKeyConstraint(['transporter_id'], ['vendors.id'], name='trip_sheets_ibfk_2'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='trip_sheets_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('trip_sheets', schema=None) as batch_op:
        batch_op.create_index('ix_trip_sheets_trip_number', ['trip_number'], unique=True)

    # ### end Alembic commands ###
