"""remove_logistics_module

Revision ID: d9873b09a753
Revises: 38a24c246f07
Create Date: 2026-05-26 17:00:26.028010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd9873b09a753'
down_revision: Union[str, Sequence[str], None] = '38a24c246f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("SET FOREIGN_KEY_CHECKS = 0;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS transport_quotations;")
    op.execute("DROP TABLE IF EXISTS receipt_confirmations;")
    op.execute("DROP TABLE IF EXISTS transport_documents;")
    op.execute("DROP TABLE IF EXISTS mda_items;")
    op.execute("DROP TABLE IF EXISTS material_dispatch_advice;")
    op.execute("DROP TABLE IF EXISTS shipment_tracking;")
    op.execute("DROP TABLE IF EXISTS transport_orders;")
    op.execute("DROP TABLE IF EXISTS transport_requirements;")
    op.execute("SET FOREIGN_KEY_CHECKS = 1;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("SET FOREIGN_KEY_CHECKS = 0;")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wave_plans', schema=None) as batch_op:
        batch_op.alter_column('wave_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('warehouse_racks', schema=None) as batch_op:
        batch_op.create_index('uq_wh_rack', ['line_id', 'code'], unique=True)

    with op.batch_alter_table('warehouse_locations', schema=None) as batch_op:
        batch_op.create_index('uq_wh_loc', ['warehouse_id', 'code'], unique=True)

    with op.batch_alter_table('warehouse_lines', schema=None) as batch_op:
        batch_op.create_index('uq_wh_line', ['location_id', 'code'], unique=True)

    with op.batch_alter_table('warehouse_bins', schema=None) as batch_op:
        batch_op.create_index('uq_wh_bin', ['rack_id', 'code'], unique=True)

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_vendors_vendor_type_id', ['vendor_type_id'], unique=False)
        batch_op.create_index('ix_vendors_vendor_category_id', ['vendor_category_id'], unique=False)
        batch_op.create_index('idx_vendor_license_expiry', ['drug_license_expiry'], unique=False)
        batch_op.alter_column('onboarded_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('vendor_ratings', schema=None) as batch_op:
        batch_op.alter_column('period_to',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('period_from',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('vendor_items', schema=None) as batch_op:
        batch_op.create_index('idx_vendor_items_item_id', ['item_id'], unique=False)

    with op.batch_alter_table('vendor_contracts', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_organization_id', ['organization_id'], unique=False)

    with op.batch_alter_table('user_warehouses', schema=None) as batch_op:
        batch_op.create_index('uq_user_wh', ['user_id', 'warehouse_id'], unique=True)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index('uq_user_role', ['user_id', 'role_id'], unique=True)

    with op.batch_alter_table('user_projects', schema=None) as batch_op:
        batch_op.create_index('uq_user_project', ['user_id', 'project_id'], unique=True)

    with op.batch_alter_table('user_item_permissions', schema=None) as batch_op:
        batch_op.create_index('uq_user_item_permissions_scope', ['user_id', 'entity_type', 'entity_id', 'action'], unique=True)

    with op.batch_alter_table('user_group_permissions', schema=None) as batch_op:
        batch_op.create_index('uq_ugp_group_entity_action', ['group_id', 'entity_type', 'entity_id', 'action'], unique=True)
        batch_op.create_index('ix_ugp_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.alter_column('action',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               nullable=False,
               existing_server_default=sa.text("'view'"))

    with op.batch_alter_table('user_group_members', schema=None) as batch_op:
        batch_op.create_index('uq_ugm_group_user', ['group_id', 'user_id'], unique=True)

    with op.batch_alter_table('uom_conversions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('conversion_factor',
               existing_type=sa.Numeric(precision=24, scale=12),
               type_=mysql.DECIMAL(precision=15, scale=6),
               existing_nullable=False)

    with op.batch_alter_table('uom_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('uom', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_uom_category_id', ['category_id'], unique=False)
        batch_op.alter_column('abbreviation',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.alter_column('expected_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('transfer_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('stock_transfer_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('stock_ledger', schema=None) as batch_op:
        batch_op.create_index('idx_stock_ledger_item_wh_date', ['item_id', 'warehouse_id', 'posting_date'], unique=False)
        batch_op.alter_column('posting_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('transaction_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('grn', 'putaway', 'pick', 'pack', 'dispatch', 'transfer_in', 'transfer_out', 'adjustment', 'consumption', 'return', 'opening', 'material_issue', 'stock_entry'),
               existing_nullable=False)

    with op.batch_alter_table('stock_balance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_stock_balance_key', type_='unique')
        batch_op.drop_index('idx_sb_composite')
        batch_op.create_index('uq_stock_bal', ['item_id', 'warehouse_id', 'bin_id', 'batch_id'], unique=True)

    with op.batch_alter_table('stock_audits', schema=None) as batch_op:
        batch_op.alter_column('audit_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('stock_audit_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('serial_numbers', schema=None) as batch_op:
        batch_op.create_index('uq_item_serial', ['item_id', 'serial_number'], unique=True)

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.alter_column('delivery_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('order_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index('uq_role_perm', ['role_id', 'permission_id'], unique=True)

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('valid_until',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('quotation_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('putaway_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_putaway_items_batch_id', 'batches', ['batch_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('batch_id',
               existing_type=mysql.BIGINT(),
               nullable=True)

    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.alter_column('return_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('purchase_return_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('expected_delivery_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('po_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('price_lists', schema=None) as batch_op:
        batch_op.alter_column('valid_to',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('valid_from',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('price_list_items', schema=None) as batch_op:
        batch_op.create_index('idx_price_list_items_item_id', ['item_id'], unique=False)
        batch_op.alter_column('valid_to',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('valid_from',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('picking_orders', schema=None) as batch_op:
        batch_op.create_index('idx_picking_orders_mi', ['material_issue_id'], unique=False)

    with op.batch_alter_table('picking_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index('uq_perm', ['module', 'action', 'resource'], unique=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('packing_orders', schema=None) as batch_op:
        batch_op.create_index('idx_packing_orders_mi', ['material_issue_id'], unique=False)

    with op.batch_alter_table('packing_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('number_series', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('uq_ns_module_doc_fy')
        batch_op.create_index('uq_ns', ['prefix', 'module', 'fiscal_year'], unique=True)
        batch_op.create_index('ix_ns_module_doc_fy', ['module', 'document_type', 'fiscal_year'], unique=False)
        batch_op.create_index('idx_numseries_fy', ['module', 'document_type', 'fiscal_year'], unique=False)

    with op.batch_alter_table('mr_indent_links', schema=None) as batch_op:
        batch_op.create_index('uq_mril_mr_indent_item', ['mr_id', 'indent_item_id'], unique=True)
        batch_op.create_index('ix_mril_mr', ['mr_id'], unique=False)
        batch_op.create_index('ix_mril_indent', ['indent_id'], unique=False)

    with op.batch_alter_table('material_requests', schema=None) as batch_op:
        batch_op.create_index('idx_mr_indent', ['indent_id'], unique=False)
        batch_op.alter_column('required_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('request_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('material_request_items', schema=None) as batch_op:
        batch_op.create_index('idx_material_request_items_item_id', ['item_id'], unique=False)

    with op.batch_alter_table('material_issues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_material_issues_destination_warehouse', 'warehouses', ['destination_warehouse_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('issue_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('material_issue_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_material_issue_items_batch_id', 'batches', ['batch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_material_issue_items_bin_id', 'warehouse_bins', ['bin_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('landed_costs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_treatment', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=40), nullable=True))

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('idx_je_org', ['organization_id'], unique=False)
        batch_op.alter_column('entry_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume_uom', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('weight', mysql.DECIMAL(precision=10, scale=3), nullable=True))
        batch_op.add_column(sa.Column('generic_name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('weight_uom', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('volume', mysql.DECIMAL(precision=10, scale=3), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('uq_items_name_active_ci', [], unique=True)
        batch_op.create_index('ix_items_uom_category_id', ['uom_category_id'], unique=False)
        batch_op.create_index('idx_items_feature_id', ['feature_id'], unique=False)
        batch_op.create_index('idx_item_form_code', ['dosage_form_code'], unique=False)

    with op.batch_alter_table('item_packaging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width', mysql.DECIMAL(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('dimension_uom_id', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('barcode_gtin', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.add_column(sa.Column('tare_weight', mysql.DECIMAL(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('weight_uom_id', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('quantity_in_parent', mysql.DECIMAL(precision=15, scale=4), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parent_packaging_id', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('height', mysql.DECIMAL(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('length', mysql.DECIMAL(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
        batch_op.add_column(sa.Column('barcode_sscc', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.add_column(sa.Column('gross_weight', mysql.DECIMAL(precision=10, scale=4), nullable=True))
        batch_op.create_foreign_key('fk_item_packing_parent_packaging_id', 'item_packaging', ['parent_packaging_id'], ['id'])
        batch_op.create_foreign_key('fk_item_packing_dimension_uom_id', 'uom', ['dimension_uom_id'], ['id'])
        batch_op.create_foreign_key('fk_item_packing_weight_uom_id', 'uom', ['weight_uom_id'], ['id'])
        batch_op.create_index('idx_item_packaging_tree', ['item_id', 'parent_packaging_id'], unique=False)

    with op.batch_alter_table('item_features', schema=None) as batch_op:
        batch_op.create_index('ux_item_features_item_feature', ['item_id', 'feature_id'], unique=True)

    with op.batch_alter_table('item_categories', schema=None) as batch_op:
        batch_op.create_index('idx_itemcat_prefix', ['code_prefix'], unique=False)

    with op.batch_alter_table('item_attributes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('uq_attr_category_code', ['category_id', 'code'], unique=True)
        batch_op.create_index('ix_item_attributes_uom_category_id', ['uom_category_id'], unique=False)

    with op.batch_alter_table('item_attribute_values', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('uq_iav_item_attr', ['item_id', 'attribute_id'], unique=True)
        batch_op.create_index('ix_item_attribute_values_uom_category_id', ['uom_category_id'], unique=False)

    with op.batch_alter_table('issue_returns', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('invoice_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('indents', schema=None) as batch_op:
        batch_op.create_index('ix_indents_raised_by_created', ['raised_by', 'created_at'], unique=False)
        batch_op.alter_column('required_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('indent_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('indent_items', schema=None) as batch_op:
        batch_op.create_index('idx_reserved_at', ['reserved_at'], unique=False)
        batch_op.create_index('idx_fulfillment_status', ['fulfillment_status'], unique=False)

    with op.batch_alter_table('grn_items', schema=None) as batch_op:
        batch_op.create_index('idx_grn_items_item_id', ['item_id'], unique=False)
        batch_op.alter_column('expiry_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('manufacturing_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('goods_receipt_notes', schema=None) as batch_op:
        batch_op.alter_column('supplier_invoice_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('grn_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('gate_passes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'approved', 'gate_in', 'gate_out', 'completed', 'cancelled'),
               nullable=False,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('fiscal_years', schema=None) as batch_op:
        batch_op.create_index('uq_fy_org_label', ['organization_id', 'year_label'], unique=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('delivery_orders', schema=None) as batch_op:
        batch_op.alter_column('delivery_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.alter_column('cn_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('consumption_returns', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('consumption_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('consumption_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_issue_id', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_index('idx_consumption_source_issue', ['source_issue_id'], unique=False)
        batch_op.alter_column('consumption_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('chart_of_accounts', schema=None) as batch_op:
        batch_op.create_index('idx_coa_org', ['organization_id'], unique=False)

    with op.batch_alter_table('business_rules', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('business_rule_executions', schema=None) as batch_op:
        batch_op.alter_column('fired_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_brands_manufacturer', 'vendors', ['manufacturer_id'], ['id'])

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index('uq_item_batch', ['item_id', 'batch_number'], unique=True)
        batch_op.alter_column('expiry_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('manufacturing_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('barcode_registry', schema=None) as batch_op:
        batch_op.alter_column('barcode_data',
               existing_type=mysql.TEXT(),
               comment='JSON data encoded in QR',
               existing_nullable=True)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('warranty_expiry',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('purchase_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index('ix_ar_status_requested', ['status', 'requested_at'], unique=False)

    with op.batch_alter_table('approval_delegations', schema=None) as batch_op:
        batch_op.create_index('ix_appdel_delegator_active', ['delegator_id', 'is_active'], unique=False)
        batch_op.create_index('ix_appdel_delegatee_active', ['delegatee_id', 'is_active'], unique=False)

    op.create_table('transport_orders',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('order_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('requirement_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('quotation_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('vendor_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('vehicle_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('vehicle_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('driver_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('driver_contact', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('docket_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('courier_reference', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('lr_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('dispatch_date', mysql.DATETIME(), nullable=True),
    sa.Column('expected_delivery_date', sa.DATE(), nullable=True),
    sa.Column('actual_delivery_date', mysql.DATETIME(), nullable=True),
    sa.Column('transport_cost', mysql.DECIMAL(precision=15, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('status', mysql.ENUM('draft', 'confirmed', 'vehicle_assigned', 'dispatched', 'in_transit', 'delivered', 'closed', 'cancelled'), server_default=sa.text("'draft'"), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['transport_quotations.id'], name='transport_orders_ibfk_2'),
    sa.ForeignKeyConstraint(['requirement_id'], ['transport_requirements.id'], name='transport_orders_ibfk_1'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name='transport_orders_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('transport_orders', schema=None) as batch_op:
        batch_op.create_index('order_number', ['order_number'], unique=True)

    op.create_table('receipt_confirmations',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('transport_order_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('received_by', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('received_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('received_qty', mysql.DECIMAL(precision=15, scale=3), nullable=True),
    sa.Column('delivery_remarks', mysql.TEXT(), nullable=True),
    sa.Column('condition_remarks', mysql.TEXT(), nullable=True),
    sa.Column('barcode_scanned', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('scan_timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], name='receipt_confirmations_ibfk_2'),
    sa.ForeignKeyConstraint(['transport_order_id'], ['transport_orders.id'], name='receipt_confirmations_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('transport_documents',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('transport_order_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('document_type', mysql.ENUM('lr', 'docket', 'invoice', 'pod', 'other'), nullable=False),
    sa.Column('document_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('file_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('uploaded_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['transport_order_id'], ['transport_orders.id'], name='transport_documents_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mda_items',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('mda_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('item_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('batch_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('qty', mysql.DECIMAL(precision=15, scale=3), nullable=False),
    sa.Column('uom_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='mda_items_ibfk_2'),
    sa.ForeignKeyConstraint(['mda_id'], ['material_dispatch_advice.id'], name='mda_items_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('material_dispatch_advice',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('mda_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('transport_order_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('dispatch_warehouse_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('destination', mysql.TEXT(), nullable=True),
    sa.Column('dispatch_date', mysql.DATETIME(), nullable=True),
    sa.Column('vehicle_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('docket_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('lr_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('total_packages', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('total_weight', mysql.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_warehouse_id'], ['warehouses.id'], name='material_dispatch_advice_ibfk_2'),
    sa.ForeignKeyConstraint(['transport_order_id'], ['transport_orders.id'], name='material_dispatch_advice_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('material_dispatch_advice', schema=None) as batch_op:
        batch_op.create_index('mda_number', ['mda_number'], unique=True)

    op.create_table('shipment_tracking',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('transport_order_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('vehicle_assigned', 'loading', 'dispatched', 'in_transit', 'reached_destination', 'unloading', 'delivered'), nullable=False),
    sa.Column('status_timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('location_description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('barcode_scanned', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('updated_by', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['transport_order_id'], ['transport_orders.id'], name='shipment_tracking_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('transport_requirements',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('requirement_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('requirement_type', mysql.ENUM('material_dispatch', 'inter_warehouse', 'vendor_delivery', 'customer_shipment'), nullable=False),
    sa.Column('dispatch_warehouse_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('destination_warehouse_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('dispatch_address', mysql.TEXT(), nullable=True),
    sa.Column('destination_address', mysql.TEXT(), nullable=True),
    sa.Column('material_description', mysql.TEXT(), nullable=True),
    sa.Column('total_qty', mysql.DECIMAL(precision=15, scale=3), nullable=True),
    sa.Column('total_weight', mysql.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('total_volume', mysql.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('vehicle_type_required', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('expected_dispatch_date', sa.DATE(), nullable=True),
    sa.Column('expected_delivery_date', sa.DATE(), nullable=True),
    sa.Column('priority', mysql.ENUM('low', 'medium', 'high', 'urgent'), server_default=sa.text("'medium'"), nullable=True),
    sa.Column('status', mysql.ENUM('draft', 'open', 'quotation_received', 'vendor_selected', 'in_transit', 'delivered', 'closed', 'cancelled'), server_default=sa.text("'draft'"), nullable=True),
    sa.Column('reference_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('reference_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.Column('created_by', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_warehouse_id'], ['warehouses.id'], name='transport_requirements_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('transport_requirements', schema=None) as batch_op:
        batch_op.create_index('requirement_number', ['requirement_number'], unique=True)

    op.create_table('transport_quotations',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('requirement_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('vendor_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('quoted_amount', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('vehicle_available', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('vehicle_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('estimated_delivery_days', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.ENUM('submitted', 'accepted', 'rejected'), server_default=sa.text("'submitted'"), nullable=True),
    sa.Column('submitted_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['transport_requirements.id'], name='transport_quotations_ibfk_1'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name='transport_quotations_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.execute("SET FOREIGN_KEY_CHECKS = 1;")
    # ### end Alembic commands ###
