"""add_material_inward

Revision ID: f148bcadea51
Revises: 52da8998b31d
Create Date: 2026-05-20 11:58:12.243867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f148bcadea51'
down_revision: Union[str, Sequence[str], None] = '52da8998b31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_inwards',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inward_number', sa.String(length=50), nullable=False),
    sa.Column('po_id', sa.BigInteger(), nullable=True),
    sa.Column('po_number', sa.String(length=50), nullable=True),
    sa.Column('vendor_id', sa.BigInteger(), nullable=True),
    sa.Column('vendor_name_manual', sa.String(length=255), nullable=True),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('received_date', sa.DateTime(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'received', 'grn_created', 'cancelled', name='inward_status_enum'), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inward_number')
    )
    op.create_table('material_inward_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inward_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('item_name_manual', sa.String(length=255), nullable=True),
    sa.Column('ordered_qty', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('received_qty', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('uom_id', sa.BigInteger(), nullable=True),
    sa.Column('uom_manual', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['inward_id'], ['material_inwards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['uom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_inward_items')
    op.drop_table('material_inwards')
    # ### end Alembic commands ###
